# Use this compose file to setup local development environment
#version: '3.6' # defines file features
version: '3.5' # defines file features
services:
  rmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo:4.0.5
    restart: always
    ports: 
      - "27017:27017"   
  webAdmin:
    image: "dnatrack/web/admin"
    restart: always
    environment:
      "Rabbit:Endpoint": "rabbitmq://rmq:5672"
      "Rabbit:Username": "rabbitmq"
      "Rabbit:Password": "rabbitmq"
    ports: 
      - "8000:80"
    volumes:
      - ./appsettings.json:/etc/config/appsettings.json:ro
  webClient:
    image: "dnatrack/web/client"
    restart: always
    ports: 
      - "8001:80"
    volumes:
      - ./appsettings.json:/etc/config/appsettings.json:ro
  analysis:
    image: "dnatrack/web/analysis"
    restart: always
    volumes:
      - ./appsettings.json:/etc/config/appsettings.json:ro

#networks
#volumes
