apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: validator
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: validator
            imagePullPolicy: Always
            image: arukim/dnatrack-job-validator:v1
            volumeMounts:
                - name: app-config
                  mountPath: /etc/config
          volumes:
              - name: app-config
                configMap:
                  name: app
          restartPolicy: Never
